services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  ml_client:
    build:
      context: ./machine-learning-client
      dockerfile: Dockerfile
    container_name: ml_client
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/containerapp
    ports:
      - "5000:5000"
    networks:
      - app_network

  web_app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
      - ml_client
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - ./web-app/static/css:/app/static/css

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
